### PR TITLE
dispatch change event after filling form field

### LINKED ISSUE #638: Angular Apps do not detect input
An increasing amount of webpages use Angular JS to build their Login-Forms. Sadly, Angular is not able to detect input from KeeFox (mostly noticeable because of the required-validation failing).

I guess the Issue is because Angular holds it's own data model and only updates it upon interaction. KeeFox's way of setting the values seems not to trigger the onChange event though.

In MY angular login forms I explicitly load username/password with jQuery. But we cannot expect every developert to do this and I doubt that angular changes it's behaviour in near future.

Request: make KeeFox work with angular.

Sample Page:
https://ebanking.raiffeisen.ch/entry/#/login

### PR DESCRIPTION
**Pull request by DanCech**
This change fixes #638 and is a duplicate of #739, but with white-space changes removed.

### CODE REVIEW

**Comment by levicki** [comment]
@DanCech How much work would it be to add a settings checkbox which activates this change conditionally and is disabled by default?

**Comment by luckyrat** [comment]
Thanks @DanCech. I would accept this into v1.7 if it were implemented as @levicki suggests - optional and disabled by default.

We're splitting the conversation a little bit from #739 but it's relevant here too: My concern is that this is not something that benefits a majority of form-filling operations (albeit a non-trivial number as you point out) and since I have no time to give it the testing such a change deserves or put it through the beta-testing period a change like this should receive, I don't feel the risk outweighs the benefit.

That risk/reward balance is completely shifted if we can include it as an optional setting - doing so would also give us some useful real-world feedback ready for v2.0 later in the year where we could consider removing the setting entirely and going for a default enabled state if we don't hear of significant negative side-effects from the change.

Please add it as a new checkbox at the end of the "Filling Entries" tab. You'll need to add a bit of code to each of these files:

Firefox addon/KeeFox/modules/DataMigration.js 
Firefox addon/KeeFox/chrome/locale/en-US/keefox.properties
Firefox addon/KeeFox/defaults/preferences/prefs.js
Firefox addon/KeeFox/chrome/content/options.js
Firefox addon/KeeFox/chrome/content/options.xul

Thanks,
Chris

**Comment by hackel** [comment]
FYI this same approach is also used here:
https://github.com/pfn/passifox/blob/master/chromeipass/chromeipass.js#L1415

It's been in place in that extension since June.  I realise that's not at all the same as putting it through a proper testing process in KeeFox, just some support that the idea is sound.  We might also want to trigger the `input` event as they do.

**Comment by DanCech** [comment]
@hackel thanks for the data point! If gating it behind a toggle is what it'll take to get it into 1.7 I'd be happy to do that when I can find time, though I would agree with you that it's an established pattern and that not dispatching the event(s) is a bug rather than dispatching them being a feature.

**Comment by luckyrat** [comment]
@DanCech Sounds good. I'm planning to send the strings off for translation just after the 13th May so the translation team have a couple of weeks before I release the 1.7 beta around the end of May.

**Comment by luckyrat** [comment]
@EmTeedee implemented the optional version of this in #778. Thanks everyone for your efforts on this issue.

**Pull request closed without merging**
